# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telagrafico.ui'
#
# Created: Thu Nov 26 11:42:57 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.edX5 = QtGui.QLineEdit(self.frame)
        self.edX5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edX5.setObjectName(_fromUtf8("edX5"))
        self.horizontalLayout.addWidget(self.edX5)
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.edX4 = QtGui.QLineEdit(self.frame)
        self.edX4.setInputMask(_fromUtf8(""))
        self.edX4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edX4.setObjectName(_fromUtf8("edX4"))
        self.horizontalLayout.addWidget(self.edX4)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.edX3 = QtGui.QLineEdit(self.frame)
        self.edX3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edX3.setObjectName(_fromUtf8("edX3"))
        self.horizontalLayout.addWidget(self.edX3)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.edX2 = QtGui.QLineEdit(self.frame)
        self.edX2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edX2.setObjectName(_fromUtf8("edX2"))
        self.horizontalLayout.addWidget(self.edX2)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.edX1 = QtGui.QLineEdit(self.frame)
        self.edX1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edX1.setObjectName(_fromUtf8("edX1"))
        self.horizontalLayout.addWidget(self.edX1)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.edX0 = QtGui.QLineEdit(self.frame)
        self.edX0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edX0.setObjectName(_fromUtf8("edX0"))
        self.horizontalLayout.addWidget(self.edX0)
        self.verticalLayout.addWidget(self.frame)
        self.frLimites = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frLimites.sizePolicy().hasHeightForWidth())
        self.frLimites.setSizePolicy(sizePolicy)
        self.frLimites.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frLimites.setFrameShadow(QtGui.QFrame.Plain)
        self.frLimites.setObjectName(_fromUtf8("frLimites"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frLimites)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_6 = QtGui.QLabel(self.frLimites)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_2.addWidget(self.label_6)
        self.edXmin = QtGui.QLineEdit(self.frLimites)
        self.edXmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edXmin.setObjectName(_fromUtf8("edXmin"))
        self.horizontalLayout_2.addWidget(self.edXmin)
        self.label_8 = QtGui.QLabel(self.frLimites)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_2.addWidget(self.label_8)
        self.edXmax = QtGui.QLineEdit(self.frLimites)
        self.edXmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edXmax.setObjectName(_fromUtf8("edXmax"))
        self.horizontalLayout_2.addWidget(self.edXmax)
        self.label_9 = QtGui.QLabel(self.frLimites)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_2.addWidget(self.label_9)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_7 = QtGui.QLabel(self.frLimites)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_2.addWidget(self.label_7)
        self.edYmin = QtGui.QLineEdit(self.frLimites)
        self.edYmin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edYmin.setObjectName(_fromUtf8("edYmin"))
        self.horizontalLayout_2.addWidget(self.edYmin)
        self.label_11 = QtGui.QLabel(self.frLimites)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_2.addWidget(self.label_11)
        self.edYmax = QtGui.QLineEdit(self.frLimites)
        self.edYmax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.edYmax.setObjectName(_fromUtf8("edYmax"))
        self.horizontalLayout_2.addWidget(self.edYmax)
        self.label_10 = QtGui.QLabel(self.frLimites)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_2.addWidget(self.label_10)
        self.btFaca = QtGui.QPushButton(self.frLimites)
        self.btFaca.setObjectName(_fromUtf8("btFaca"))
        self.horizontalLayout_2.addWidget(self.btFaca)
        self.verticalLayout.addWidget(self.frLimites)
        self.widget = QtGui.QWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuGrafico = QtGui.QMenu(self.menubar)
        self.menuGrafico.setObjectName(_fromUtf8("menuGrafico"))
        self.menuAjuda = QtGui.QMenu(self.menubar)
        self.menuAjuda.setObjectName(_fromUtf8("menuAjuda"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionTracar = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("grafico.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTracar.setIcon(icon)
        self.actionTracar.setObjectName(_fromUtf8("actionTracar"))
        self.actionSair = QtGui.QAction(MainWindow)
        self.actionSair.setObjectName(_fromUtf8("actionSair"))
        self.actionLimites = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("preferences-system-windows-actions.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLimites.setIcon(icon1)
        self.actionLimites.setObjectName(_fromUtf8("actionLimites"))
        self.menuGrafico.addAction(self.actionTracar)
        self.menuGrafico.addAction(self.actionLimites)
        self.menuGrafico.addSeparator()
        self.menuGrafico.addAction(self.actionSair)
        self.menubar.addAction(self.menuGrafico.menuAction())
        self.menubar.addAction(self.menuAjuda.menuAction())
        self.toolBar.addAction(self.actionTracar)
        self.toolBar.addAction(self.actionLimites)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.edX5.setText(_translate("MainWindow", "1.0", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>x<span style=\" vertical-align:super;\">5</span>+</p></body></html>", None))
        self.edX4.setText(_translate("MainWindow", "0.0", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>x<span style=\" vertical-align:super;\">4</span>+</p></body></html>", None))
        self.edX3.setText(_translate("MainWindow", "0.0", None))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>x<span style=\" vertical-align:super;\">3</span>+</p></body></html>", None))
        self.edX2.setText(_translate("MainWindow", "0.0", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>x<span style=\" vertical-align:super;\">2</span>+</p></body></html>", None))
        self.edX1.setText(_translate("MainWindow", "0.0", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>x+</p></body></html>", None))
        self.edX0.setText(_translate("MainWindow", "0.0", None))
        self.label_6.setText(_translate("MainWindow", "X", None))
        self.edXmin.setText(_translate("MainWindow", "-10.0", None))
        self.label_8.setText(_translate("MainWindow", "min", None))
        self.edXmax.setText(_translate("MainWindow", "10.0", None))
        self.label_9.setText(_translate("MainWindow", "max", None))
        self.label_7.setText(_translate("MainWindow", "Y", None))
        self.edYmin.setText(_translate("MainWindow", "-10.0", None))
        self.label_11.setText(_translate("MainWindow", "min", None))
        self.edYmax.setText(_translate("MainWindow", "10.0", None))
        self.label_10.setText(_translate("MainWindow", "max", None))
        self.btFaca.setText(_translate("MainWindow", "OK", None))
        self.menuGrafico.setToolTip(_translate("MainWindow", "Menu de propriedades do gráfico", None))
        self.menuGrafico.setTitle(_translate("MainWindow", "&Gráfico", None))
        self.menuAjuda.setToolTip(_translate("MainWindow", "Menu de ajuda da aplicação", None))
        self.menuAjuda.setTitle(_translate("MainWindow", "&Ajuda", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionTracar.setText(_translate("MainWindow", "&Traçar", None))
        self.actionTracar.setToolTip(_translate("MainWindow", "Traça/Atualiza o gráfico", None))
        self.actionTracar.setShortcut(_translate("MainWindow", "F5", None))
        self.actionSair.setText(_translate("MainWindow", "Sai&r", None))
        self.actionLimites.setText(_translate("MainWindow", "&Limites", None))

